### ISSUE TITLE
Python 2.7 spits out a traceback on [Error 65]

### ISSUE THREAD

**Issue by EclectickMedia** [l4m3rx/python-ping#16]
# Bug description

The current iteration of master (#15) does not operate the same as Python 3.x. See the *Execution Snippets* below.

Is this intentional? A try except block may fix the issue.

# Python 2.7 *Execution Snippet*

```
$ sudo python2 ping.py -T
Running PYTHON PING test case.

PYTHON PING 127.0.0.1 (127.0.0.1): 64 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.08 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.12 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.12 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.12 ms

----127.0.0.1 PYTHON PING Statistics----
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip (ms)  min/avg/max = 0/0.1/0


PYTHON PING 8.8.8.8 (8.8.8.8): 64 data bytes
Traceback (most recent call last):
  File "ping.py", line 456, in <module>
    for val in verbose_ping("8.8.8.8"):
  File "ping.py", line 364, in verbose_ping
    numDataBytes, ipv6=ipv6, myStats=myStats)
  File "ping.py", line 136, in single_ping
    sentTime = _send(mySocket, destIP, my_ID, mySeqNumber, numDataBytes, ipv6)
  File "ping.py", line 235, in _send
    mySocket.sendto(packet, (destIP, 1))  # Port number is irrelevant
socket.error: [Errno 65] No route to host
```

# Python 3.x *(3.5.2) Execution Snippet*

```
$ sudo python3 ping.py -T
Running PYTHON PING test case.

PYTHON PING 127.0.0.1 (127.0.0.1): 64 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.06 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.13 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.10 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.09 ms

----127.0.0.1 PYTHON PING Statistics----
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip (ms)  min/avg/max = 0/0.1/0


PYTHON PING 8.8.8.8 (8.8.8.8): 64 data bytes
General failure ([Errno 65] No route to host)
General failure ([Errno 65] No route to host)
General failure ([Errno 65] No route to host)
General failure ([Errno 65] No route to host)

----8.8.8.8 PYTHON PING Statistics----
0 packets transmitted, 0 packets received, 100.0% packet loss
```

> ... Continues with the rest of the `if __name__ == '__main__'` test block ...

**Comment by l4m3rx** [comment]
Nice catch.
Adding another exeception handler in _send() 
```
    except socket.error as e:
        print("General failure (%s)" % str(e))
        return
```
https://github.com/l4m3rx/python-ping/commit/48b9ea3cb004abc803aa232143e2cda72a9e1f3d

Should be OK now.
Give it a test.

**Comment by EclectickMedia** [comment]
Executes properly for me!

```
$ sudo python2 ping.py -T 
Running PYTHON PING test case.

PYTHON PING 127.0.0.1 (127.0.0.1): 64 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.08 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.13 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.11 ms
64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.12 ms

----127.0.0.1 PYTHON PING Statistics----
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip (ms)  min/avg/max = 0.1/0.1/0.1


PYTHON PING 8.8.8.8 (8.8.8.8): 64 data bytes
General failure ([Errno 65] No route to host)
General failure ([Errno 65] No route to host)
General failure ([Errno 65] No route to host)
General failure ([Errno 65] No route to host)
^C
----8.8.8.8 PYTHON PING Statistics----
0 packets transmitted, 0 packets received, 100.0% packet loss


(Terminated with signal 2)
```
